version: '3.7'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.x-next
    container_name: verdaccio-docker-local-storage-vol
    ports:
      - "4873:4873"
    expose:
      - 4873
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
        - "./plugins:/verdaccio/plugins"

volumes:
  verdaccio:
    driver: local

